(() => {
  const messages = {
    ru: {
      nav_home:'Главная', nav_catalog:'Каталог', nav_favorites:'Избранное', nav_profile:'Профиль', nav_login:'Войти', nav_logout:'Выйти', language_switcher:'Язык интерфейса', main_navigation:'Основная навигация', legal_navigation:'Правовая информация',
      loading:'Загружаем кино…', retry:'Повторить', retry_loading:'Повторить загрузку', go_catalog:'Перейти в каталог', all_catalog:'Весь каталог →', footer_tagline:'Мир кыргызского кино.', footer_note:'Учебный каталог кыргызского кино', rights_holders:'Правообладателям', takedown:'Политика удаления контента',
      no_rating:'Без оценки', poster:'Постер', poster_unavailable:'Постер недоступен', popular:'Популярное', newest:'Новинки', top_rating:'Высокий рейтинг', kyrgyz_cinema:'Кыргызское кино', new_movies:'Новые фильмы', audience_choice:'Выбор зрителей',
      hero_loading:'Загружается рекомендуемый фильм', hero_empty_label:'Рекомендуемый фильм пока не выбран', hero_empty_title:'Скоро здесь будет премьера', hero_empty_text:'Добавьте опубликованный фильм, чтобы он появился на главной странице.', open_catalog:'Открыть каталог', recommended:'КиноОрдо рекомендует', details:'Смотреть подробнее',
      collection_error:'Не удалось загрузить подборку', collection_empty:'Здесь пока нет фильмов', collection_empty_text:'Подборка появится после добавления фильмов в каталог.', continue_watching:'Продолжить просмотр', watch_history:'История просмотров', continue_from:'Продолжить с {time}', watch_progress:'Прогресс просмотра', remove_history:'Удалить из истории', clear_history:'Очистить историю', history_cleared:'История просмотров очищена',
      catalog_collection:'Коллекция', catalog_title:'Каталог фильмов', found:'Найдено: {count}', search_placeholder:'Название или описание', all_genres:'Все жанры', year:'Год', apply:'Применить', reset:'Сбросить', nothing_found:'Ничего не найдено', nothing_found_text:'Попробуйте изменить запрос или сбросить фильтры.', sort_newest:'По дате добавления', sort_title:'По названию', sort_rating:'По рейтингу', pages:'Страницы каталога', back:'← Назад', next:'Дальше →', page_of:'Страница {page} из {total}',
      account:'Аккаунт', register:'Регистрация', login:'Вход', username:'Имя пользователя', password:'Пароль', repeat_password:'Повторите пароль', username_example:'Например, azam', password_min:'Минимум 8 символов', repeat_password_hint:'Введите пароль ещё раз', create_account:'Создать аккаунт', already_registered:'Уже зарегистрированы?', no_account:'Нет аккаунта?', forgot_password:'Забыли пароль?', passwords_mismatch:'Пароли не совпадают.', check_data:'Проверьте данные:', account_created:'Аккаунт создан', logged_in:'Вы вошли', logged_out:'Вы вышли',
      account_security:'Безопасность аккаунта', reset_password:'Восстановление пароля', reset_intro:'Укажите email аккаунта. Ответ будет одинаковым независимо от того, зарегистрирован адрес или нет.', send_instruction:'Отправить инструкцию', return_login:'Вернуться ко входу', new_password:'Новый пароль', change_password:'Изменить пароль', missing_reset_token:'В ссылке отсутствует токен восстановления.', done:'Готово', password_changed:'Пароль изменён',
      email_confirmation:'Подтверждение адреса', email_confirm_intro:'Нажмите кнопку, чтобы подтвердить новый email. Ссылка сработает только один раз.', confirm_email:'Подтвердить email', missing_email_token:'В ссылке отсутствует токен подтверждения.', return_profile:'Вернуться в профиль',
      personal_profile:'Личный профиль', profile_intro:'Здесь хранятся данные вашего аккаунта КиноОрдо.', registration_date:'Дата регистрации', not_specified:'Не указан', change_email:'Изменить email', new_email:'Новый email', email_change_intro:'Новый адрес будет сохранён только после перехода по ссылке из письма.', send_confirmation:'Отправить подтверждение', open_favorites:'Открыть избранное', favorites_empty:'Здесь пока нет фильмов',
      network_title:'Нет соединения с сервером', network_message:'Проверьте интернет и убедитесь, что КиноОрдо запущен.', unauthorized_title:'Нужно войти в аккаунт', unauthorized_message:'Сессия завершилась или для этого действия требуется авторизация.', forbidden_title:'Доступ запрещён', forbidden_message:'У вашего аккаунта нет прав для выполнения этого действия.', not_found_title:'Страница не найдена', not_found_message:'Возможно, фильм удалён или адрес указан неправильно.', throttled_title:'Слишком много запросов', throttled_message:'Защита от спама временно ограничила запросы. Подождите немного и попробуйте снова.', server_title:'Ошибка на сервере', server_message:'Мы не смогли обработать запрос. Попробуйте ещё раз немного позже.', timeout_title:'Сервер отвечает слишком долго', request_failed:'Не удалось выполнить запрос', try_again:'Попробуйте ещё раз.', request_error:'Ошибка запроса. Попробуйте ещё раз.', network_error:'Сетевая ошибка', error_status:'Ошибка {status}', timeout_message:'Сервер не ответил за 10 секунд. Проверьте соединение и повторите загрузку.', offline:'Соединение с интернетом потеряно', online:'Соединение восстановлено',
      minutes:'мин', director:'Режиссёр', cast:'В ролях', not_listed:'не указан', not_listed_plural:'не указаны', watch:'Смотреть', trailer:'Трейлер', movie_actions:'Действия с фильмом', save_movie:'Сохранить фильм', personal_rating:'Личная оценка',
      favorite_add:'В избранное', favorite_added:'✓ В избранном', favorite_toast:'Добавлено в избранное', favorite_removed:'Удалено из избранного', rating_of:'{value} из 5', not_rated:'Пока не оценён', your_rating:'Ваша оценка: {value} из 5', comments:'Комментарии', discussion:'Обсуждение', comment_placeholder:'Поделитесь впечатлением о фильме', your_comment:'Ваш комментарий', send:'Отправить', comment_empty:'Напишите комментарий перед отправкой.', comment_published:'Комментарий опубликован', comments_empty:'Комментариев пока нет. Начните обсуждение первым.', login_to_discuss:'Войдите в аккаунт, чтобы присоединиться к обсуждению.',
      video_player:'Видеоплеер', play:'Воспроизвести', pause:'Пауза', video_error:'Видео не удалось загрузить', video_error_hint:'Проверьте подключение и повторите попытку.', playback_blocked:'Браузер не разрешил воспроизведение', back_10:'Назад на 10 секунд', forward_10:'Вперёд на 10 секунд', playback_position:'Позиция воспроизведения', mute:'Выключить звук', unmute:'Включить звук', volume:'Громкость', speed:'Скорость', fullscreen:'Полноэкранный режим', exit_fullscreen:'Выйти из полноэкранного режима', fullscreen_unsupported:'Полноэкранный режим не поддерживается', fullscreen_unavailable:'Полноэкранный режим недоступен', player_shortcuts:'Пробел — пауза · ← → — 10 сек · F — полный экран', embed_hint:'Скорость и полный экран доступны в панели встроенного плеера.', external_movie:'Фильм доступен на внешней площадке', external_hint:'Просмотр откроется в новой безопасной вкладке.', open_legal_source:'Открыть легальный источник', video_unavailable:'Видео временно недоступно', video_unavailable_hint:'Мы сохранили информацию о фильме. Источник просмотра появится позже.',
      rights_sources:'Права и источники', content_info:'Информация о контенте', material:'Материал', rights_holder:'Правообладатель', license:'Лицензия', verification:'Проверка', rights_details:'Сведения о правах', open_source:'Открыть источник', source:'источник', being_clarified:'уточняется', pending_review:'ожидает проверки',
      api_reset_accepted:'Если аккаунт с таким email существует, мы отправили инструкции по восстановлению.', api_password_changed:'Пароль изменён. Теперь вы можете войти с новым паролем.', api_email_sent:'Мы отправили письмо на новый адрес. Email изменится только после подтверждения.', api_invalid_token:'Ссылка недействительна, уже использована или срок её действия истёк.', api_invalid_login:'Неверное имя пользователя или пароль.', api_username_short:'Имя пользователя должно содержать минимум 3 символа.', api_username_taken:'Это имя пользователя уже занято.', api_email_taken:'Этот email уже используется.'
    },
    ky: {
      nav_home:'Башкы бет', nav_catalog:'Каталог', nav_favorites:'Тандалгандар', nav_profile:'Профиль', nav_login:'Кирүү', nav_logout:'Чыгуу', language_switcher:'Интерфейстин тили', main_navigation:'Негизги навигация', legal_navigation:'Укуктук маалымат',
      loading:'Тасмалар жүктөлүүдө…', retry:'Кайталоо', retry_loading:'Кайра жүктөө', go_catalog:'Каталогго өтүү', all_catalog:'Толук каталог →', footer_tagline:'Кыргыз тасмаларынын дүйнөсү.', footer_note:'Кыргыз киносуна арналган окуу каталогу', rights_holders:'Укук ээлерине', takedown:'Контентти өчүрүү саясаты',
      no_rating:'Баалана элек', poster:'Постер', poster_unavailable:'Постер жеткиликсиз', popular:'Популярдуу', newest:'Жаңы тасмалар', top_rating:'Жогорку рейтинг', kyrgyz_cinema:'Кыргыз киносу', new_movies:'Жаңы тасмалар', audience_choice:'Көрүүчүлөрдүн тандоосу',
      hero_loading:'Сунушталган тасма жүктөлүүдө', hero_empty_label:'Сунушталган тасма тандала элек', hero_empty_title:'Жакында бул жерде премьера болот', hero_empty_text:'Башкы бетке чыгаруу үчүн жарыяланган тасманы кошуңуз.', open_catalog:'Каталогду ачуу', recommended:'КиноОрдо сунуштайт', details:'Толук көрүү',
      collection_error:'Тасмалар топтомун жүктөө мүмкүн болгон жок', collection_empty:'Азырынча тасмалар жок', collection_empty_text:'Каталогго тасмалар кошулгандан кийин топтом пайда болот.', continue_watching:'Көрүүнү улантуу', watch_history:'Көрүү тарыхы', continue_from:'{time} жеринен улантуу', watch_progress:'Көрүү прогресси', remove_history:'Тарыхтан өчүрүү', clear_history:'Тарыхты тазалоо', history_cleared:'Көрүү тарыхы тазаланды',
      catalog_collection:'Жыйнак', catalog_title:'Тасмалар каталогу', found:'Табылды: {count}', search_placeholder:'Аталышы же сүрөттөмөсү', all_genres:'Бардык жанрлар', year:'Жылы', apply:'Колдонуу', reset:'Тазалоо', nothing_found:'Эч нерсе табылган жок', nothing_found_text:'Суроону өзгөртүңүз же чыпкаларды тазалаңыз.', sort_newest:'Кошулган күнү боюнча', sort_title:'Аталышы боюнча', sort_rating:'Рейтинг боюнча', pages:'Каталог барактары', back:'← Артка', next:'Кийинки →', page_of:'{page} / {total} барак',
      account:'Аккаунт', register:'Катталуу', login:'Кирүү', username:'Колдонуучунун аты', password:'Сырсөз', repeat_password:'Сырсөздү кайталаңыз', username_example:'Мисалы, azam', password_min:'Кеминде 8 белги', repeat_password_hint:'Сырсөздү кайра жазыңыз', create_account:'Аккаунт түзүү', already_registered:'Катталгансызбы?', no_account:'Аккаунтуңуз жокпу?', forgot_password:'Сырсөздү унуттуңузбу?', passwords_mismatch:'Сырсөздөр дал келбейт.', check_data:'Маалыматты текшериңиз:', account_created:'Аккаунт түзүлдү', logged_in:'Сиз кирдиңиз', logged_out:'Сиз чыктыңыз',
      account_security:'Аккаунттун коопсуздугу', reset_password:'Сырсөздү калыбына келтирүү', reset_intro:'Аккаунттун email дарегин жазыңыз. Дарек катталганына карабастан жооп бирдей болот.', send_instruction:'Нускама жөнөтүү', return_login:'Кирүүгө кайтуу', new_password:'Жаңы сырсөз', change_password:'Сырсөздү өзгөртүү', missing_reset_token:'Шилтемеде калыбына келтирүү токени жок.', done:'Даяр', password_changed:'Сырсөз өзгөртүлдү',
      email_confirmation:'Даректи ырастоо', email_confirm_intro:'Жаңы email дарегин ырастоо үчүн баскычты басыңыз. Шилтеме бир жолу гана иштейт.', confirm_email:'Email дарегин ырастоо', missing_email_token:'Шилтемеде ырастоо токени жок.', return_profile:'Профилге кайтуу',
      personal_profile:'Жеке профиль', profile_intro:'Бул жерде КиноОрдо аккаунтуңуздун маалыматы сакталат.', registration_date:'Катталган күнү', not_specified:'Көрсөтүлгөн эмес', change_email:'Email өзгөртүү', new_email:'Жаңы email', email_change_intro:'Жаңы дарек каттагы шилтеме ачылгандан кийин гана сакталат.', send_confirmation:'Ырастоону жөнөтүү', open_favorites:'Тандалгандарды ачуу', favorites_empty:'Азырынча тасмалар жок',
      network_title:'Сервер менен байланыш жок', network_message:'Интернетти жана КиноОрдо иштеп жатканын текшериңиз.', unauthorized_title:'Аккаунтка кирүү керек', unauthorized_message:'Сеанс аяктады же бул аракет үчүн авторизация керек.', forbidden_title:'Кирүүгө тыюу салынган', forbidden_message:'Аккаунтуңузда бул аракетке укук жок.', not_found_title:'Барак табылган жок', not_found_message:'Тасма өчүрүлгөн же дарек туура эмес болушу мүмкүн.', throttled_title:'Өтө көп сурам', throttled_message:'Спамдан коргоо сурамдарды убактылуу чектеди. Бир аздан кийин кайталаңыз.', server_title:'Серверде ката кетти', server_message:'Сурамды иштетүү мүмкүн болгон жок. Кийинчерээк кайталаңыз.', timeout_title:'Сервер өтө жай жооп берүүдө', request_failed:'Сурам аткарылган жок', try_again:'Кайра аракет кылыңыз.', request_error:'Сурамда ката кетти. Кайра аракет кылыңыз.', network_error:'Тармак катасы', error_status:'Ката {status}', timeout_message:'Сервер 10 секундда жооп берген жок. Байланышты текшерип, кайра жүктөңүз.', offline:'Интернет байланышы үзүлдү', online:'Интернет байланышы калыбына келди',
      minutes:'мүн', director:'Режиссёр', cast:'Ролдордо', not_listed:'көрсөтүлгөн эмес', not_listed_plural:'көрсөтүлгөн эмес', watch:'Көрүү', trailer:'Трейлер', movie_actions:'Тасма менен аракеттер', save_movie:'Тасманы сактоо', personal_rating:'Жеке баа',
      favorite_add:'Тандалгандарга', favorite_added:'✓ Тандалган', favorite_toast:'Тандалгандарга кошулду', favorite_removed:'Тандалгандардан өчүрүлдү', rating_of:'5тен {value}', not_rated:'Азырынча баалана элек', your_rating:'Сиздин бааңыз: 5тен {value}', comments:'Комментарийлер', discussion:'Талкуу', comment_placeholder:'Тасма тууралуу оюңузду бөлүшүңүз', your_comment:'Сиздин комментарий', send:'Жөнөтүү', comment_empty:'Жөнөтүүдөн мурун комментарий жазыңыз.', comment_published:'Комментарий жарыяланды', comments_empty:'Азырынча комментарий жок. Талкууну биринчи баштаңыз.', login_to_discuss:'Талкууга кошулуу үчүн аккаунтка кириңиз.',
      video_player:'Видео ойноткуч', play:'Ойнотуу', pause:'Тыным', video_error:'Видео жүктөлгөн жок', video_error_hint:'Байланышты текшерип, кайра аракет кылыңыз.', playback_blocked:'Браузер ойнотууга уруксат берген жок', back_10:'10 секунд артка', forward_10:'10 секунд алдыга', playback_position:'Ойнотуу позициясы', mute:'Үндү өчүрүү', unmute:'Үндү күйгүзүү', volume:'Үн деңгээли', speed:'Ылдамдык', fullscreen:'Толук экран режими', exit_fullscreen:'Толук экрандан чыгуу', fullscreen_unsupported:'Толук экран режими колдоого алынбайт', fullscreen_unavailable:'Толук экран режими жеткиликсиз', player_shortcuts:'Боштук — тыным · ← → — 10 сек · F — толук экран', embed_hint:'Ылдамдык жана толук экран камтылган ойноткучтун панелинде жеткиликтүү.', external_movie:'Тасма тышкы аянтчада жеткиликтүү', external_hint:'Көрүү жаңы коопсуз өтмөктө ачылат.', open_legal_source:'Мыйзамдуу булакты ачуу', video_unavailable:'Видео убактылуу жеткиликсиз', video_unavailable_hint:'Тасма тууралуу маалымат сакталды. Көрүү булагы кийинчерээк чыгат.',
      rights_sources:'Укуктар жана булактар', content_info:'Контент тууралуу маалымат', material:'Материал', rights_holder:'Укук ээси', license:'Лицензия', verification:'Текшерүү', rights_details:'Укуктар тууралуу маалымат', open_source:'Булакты ачуу', source:'булак', being_clarified:'такталууда', pending_review:'текшерүүнү күтүүдө',
      api_reset_accepted:'Эгер мындай email менен аккаунт бар болсо, калыбына келтирүү нускамасын жөнөттүк.', api_password_changed:'Сырсөз өзгөртүлдү. Эми жаңы сырсөз менен кире аласыз.', api_email_sent:'Жаңы дарекке кат жөнөттүк. Email ырасталгандан кийин гана өзгөрөт.', api_invalid_token:'Шилтеме жараксыз, колдонулган же мөөнөтү бүткөн.', api_invalid_login:'Колдонуучунун аты же сырсөз туура эмес.', api_username_short:'Колдонуучунун аты кеминде 3 белгиден турушу керек.', api_username_taken:'Бул колдонуучунун аты бош эмес.', api_email_taken:'Бул email колдонулууда.'
    }
  };
  const serverKeys = Object.keys(messages.ru).filter(key => key.startsWith('api_'));
  let current = localStorage.getItem('kinoordo_language');
  if (!['ru', 'ky'].includes(current)) current = navigator.language?.toLowerCase().startsWith('ky') ? 'ky' : 'ru';
  const interpolate = (value, vars) => value.replace(/\{(\w+)\}/g, (_, key) => String(vars[key] ?? `{${key}}`));
  const t = (key, vars = {}) => interpolate(messages[current][key] || messages.ru[key] || key, vars);
  const translateServerMessage = value => { const source = String(value); const key = serverKeys.find(item => messages.ru[item] === source); return key ? t(key) : source; };
  const applyDocumentLanguage = () => { document.documentElement.lang = current; document.title = current === 'ky' ? 'КиноОрдо — кыргыз тасмалары' : 'КиноОрдо — кыргызское кино'; };
  const setLanguage = language => { if (!['ru', 'ky'].includes(language) || language === current) return; current = language; localStorage.setItem('kinoordo_language', current); applyDocumentLanguage(); window.dispatchEvent(new CustomEvent('kinoordo:languagechange', {detail:{language:current}})); };
  applyDocumentLanguage();
  window.kinoordoI18n = {t, language:() => current, setLanguage, translateServerMessage};
})();
