# Generated by Django 5.2.17 on 2026-08-20 07:33

from django.db import migrations, models


def unpublish_legacy_movies(apps, schema_editor):
    """Скрываем записи, опубликованные до появления обязательного учёта прав."""
    Movie = apps.get_model("movies", "Movie")
    Movie.objects.filter(is_published=True).update(is_published=False, is_featured=False)


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='content_source_url',
            field=models.URLField(blank=True, verbose_name='источник сведений о правах'),
        ),
        migrations.AddField(
            model_name='movie',
            name='license_type',
            field=models.CharField(choices=[('unknown', 'Не указана'), ('all_rights_reserved', 'Все права защищены'), ('licensed', 'Лицензионное соглашение'), ('permission', 'Разрешение правообладателя'), ('public_domain', 'Общественное достояние'), ('cc_by', 'Creative Commons BY'), ('cc_by_sa', 'Creative Commons BY-SA'), ('cc_by_nc', 'Creative Commons BY-NC')], default='unknown', max_length=30, verbose_name='тип лицензии'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_attribution',
            field=models.CharField(blank=True, max_length=500, verbose_name='атрибуция постера'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_source_url',
            field=models.URLField(blank=True, verbose_name='источник постера'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rights_holder',
            field=models.CharField(blank=True, max_length=255, verbose_name='правообладатель'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rights_notes',
            field=models.TextField(blank=True, help_text='В API и на сайте не показываются.', verbose_name='служебные заметки о правах'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rights_status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('verified', 'Права подтверждены'), ('rejected', 'Публикация запрещена')], default='pending', max_length=20, verbose_name='проверка прав'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_attribution',
            field=models.CharField(blank=True, max_length=500, verbose_name='атрибуция видео'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_content_type',
            field=models.CharField(choices=[('full_movie', 'Полный фильм'), ('trailer', 'Трейлер'), ('clip', 'Фрагмент'), ('demo', 'Демонстрационное видео'), ('external', 'Внешняя страница')], default='trailer', max_length=20, verbose_name='тип видеоматериала'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_source_url',
            field=models.URLField(blank=True, verbose_name='источник видео'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(unpublish_legacy_movies, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(condition=models.Q(('is_published', False), models.Q(('video_content_type', 'full_movie'), _negated=True), models.Q(('rights_status', 'verified'), models.Q(('rights_holder', ''), _negated=True), models.Q(('license_type', 'unknown'), _negated=True), models.Q(('content_source_url', ''), _negated=True)), _connector='OR'), name='published_full_movie_requires_verified_rights'),
        ),
    ]
